"""Add profile picture url to user

Revision ID: 1ffcab570e4a
Revises: 711bbc8be511
Create Date: 2025-08-13 09:49:29.907901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ffcab570e4a'
down_revision = '711bbc8be511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('profile_picture_url')

    # ### end Alembic commands ###
