"""Initial migration structure

Revision ID: 711bbc8be511
Revises:
Create Date: 2025-08-12 10:04:29.142930

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '711bbc8be511'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('rol', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehiculos',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('patente', sa.Text(), nullable=False),
    sa.Column('modelo', sa.Text(), nullable=True),
    sa.Column('zona', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patente')
    )
    op.create_table('recorridos',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('chofer_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('vehiculo_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('fecha_inicio', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_fin', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('km_inicial', sa.Numeric(), nullable=True),
    sa.Column('km_final', sa.Numeric(), nullable=True),
    sa.Column('estado_inicial', sa.Text(), nullable=True),
    sa.Column('estado_final', sa.Text(), nullable=True),
    sa.Column('combustible_litros', sa.Numeric(), nullable=True),
    sa.Column('combustible_costo', sa.Numeric(), nullable=True),
    sa.Column('combustible_foto', sa.Text(), nullable=True),
    sa.Column('observaciones_inicio', sa.Text(), nullable=True),
    sa.Column('observaciones_fin', sa.Text(), nullable=True),
    sa.Column('estado', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['chofer_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alertas',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('recorrido_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recorrido_id'], ['recorridos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('controles',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('recorrido_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.Column('detalle', sa.JSON(), nullable=True),
    sa.Column('foto', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recorrido_id'], ['recorridos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('controles')
    op.drop_table('alertas')
    op.drop_table('recorridos')
    op.drop_table('vehiculos')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
